<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Distribution_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from scipy.stats import norm

#normal distribution centers at 0 and deviation is 1

norm.pdf(0)

0.3989422804014327

In [3]:
norm.pdf(0, loc= 0, scale=10)

0.03989422804014327

In [0]:
import numpy as np
r = np.random.randn(10)

In [5]:
norm.pdf(r)

array([0.28781072, 0.39417763, 0.39773992, 0.1335932 , 0.39729874,
       0.37552831, 0.0401925 , 0.37892475, 0.29600415, 0.17703863])

In [0]:
# numpy. random. randn(d0, d1, …, dn) : creates an array of specified shape and fills it with random values as per standard normal distribution.


In [6]:
#it is advantageous to use log probability than to use actual prability because it takes less time.
norm.logpdf(r)


array([-1.24545222, -0.93095364, -0.92195696, -2.01295591, -0.9230668 ,
       -0.97942141, -3.21407486, -0.97041763, -1.21738182, -1.7313873 ])

In [7]:
#cdf cummulative distribution function

norm.cdf(r)

array([0.20951619, 0.43840404, 0.53096552, 0.06954334, 0.53620026,
       0.3639947 , 0.98392305, 0.37415408, 0.21988421, 0.10120512])

In [9]:
#log of cdf
norm.logcdf(r)

array([-1.56295425, -0.82461434, -0.6330582 , -2.66580514, -0.62324758,
       -1.01061598, -0.01620759, -0.98308759, -1.5146542 , -2.2906059 ])