<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Generating_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#generating an array of all zeroes

Z = np.zeros(10)

In [2]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#matrix 10 x10 of all zeros

z1 = np.zeros([10,10])

z1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
#matrix of all ones

ones = np.ones([10,10])
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
#matrix with random elements

#this generates numbers that are unformly distributed between 0 and 1

r1 = np.random.random([10,10])

r1

array([[0.58194998, 0.38901145, 0.73929221, 0.73969539, 0.58103707,
        0.61037815, 0.75846529, 0.08607707, 0.52989668, 0.10287211],
       [0.21533689, 0.39125667, 0.13091558, 0.52961547, 0.60804334,
        0.60741147, 0.42399156, 0.41476947, 0.53358742, 0.82509223],
       [0.16968183, 0.7037266 , 0.41553016, 0.35608311, 0.4302996 ,
        0.13381628, 0.39404302, 0.94321446, 0.13528288, 0.10215604],
       [0.22356079, 0.09449343, 0.82717858, 0.95954459, 0.44979293,
        0.83478841, 0.75088752, 0.15743726, 0.24677101, 0.01307216],
       [0.35746058, 0.3625488 , 0.68317717, 0.69138858, 0.78508587,
        0.76484213, 0.97661346, 0.76760649, 0.10011108, 0.22825655],
       [0.13730786, 0.14845292, 0.24551558, 0.83310013, 0.34748034,
        0.69507437, 0.67665067, 0.88432289, 0.47990082, 0.16888544],
       [0.63038589, 0.79315903, 0.22100188, 0.57619313, 0.91944692,
        0.24570373, 0.56079276, 0.72389866, 0.18528003, 0.18786261],
       [0.44124811, 0.93096146, 0.104694 

In [0]:
#matrix that generated numbers with gausian distribution

r1 = np.random.randn([10,10]) #this is an incorrect way

In [0]:
#the following is a correct way

r1 = np.random.randn(10,10)

In [9]:
r1

array([[-0.25266241, -1.79789587,  0.38328641,  1.12035708, -0.58734192,
         0.0793593 ,  0.27298555,  0.84565153,  0.01044537,  0.38815465],
       [ 0.94420778, -1.01648447, -1.12804449,  0.02296502, -1.54059693,
         0.68847217,  0.18105021,  2.34218552, -0.96990701, -0.61482739],
       [-1.13459953, -1.25983843, -0.65742753, -0.60227889, -0.57272647,
         0.73719739, -1.38218128, -0.57948994, -0.44217538, -0.73397983],
       [-0.13557493,  0.64364155, -1.71386412,  0.30225125, -0.22543928,
         0.55147989, -0.52615116,  0.73859385, -1.1623774 , -0.02817698],
       [ 0.56578138,  1.88367078,  1.00278398,  1.61537649, -0.59470135,
         0.45174816,  0.05820017,  0.89206433, -0.81943888, -0.28162351],
       [ 0.34343218, -1.17002374,  0.73834746,  2.31156404,  1.14793342,
        -0.46242334, -0.99207173, -0.33745227,  0.42923185, -1.2939076 ],
       [ 0.39868096, -0.90645098, -0.15687619, -0.11780622, -0.31709056,
         1.92930425,  0.34093457,  0.76511922

In [10]:
#for calculating the mean

r1.mean()

0.0688341453643165

In [11]:
#for calculating the variance

r1.var()

0.8534040989029846