<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
#Difference between an array and a list in numpy

#definging a list 
L= [1,2,3]

for e in L:
  print(e)

1
2
3


In [16]:
A= np.array([1,2,3])

for e in A:
  print(e)

1
2
3


In [0]:
#tryin append on both

L.append(4)


In [5]:
L

[1, 2, 3, 4]

In [6]:
A.append(4)

AttributeError: ignored

In [0]:
#there is nothing like append on arrays


In [0]:
#adding elements on array in a different way

L = L + [5]

In [8]:
L

[1, 2, 3, 4, 5]

In [0]:
#trying the same with arrays

A = A + [6]

In [10]:
A

array([7, 8, 9])

In [11]:
#create a new list
L2 = []

for e in L:
  L2.append(e + e)

L2

[2, 4, 6, 8, 10]

In [18]:
A+A

array([2, 4, 6])

In [0]:
#Note : the + sign in List does concatenation and the + sign in arrays does the vectorazation


In [19]:
2*A

array([2, 4, 6])

In [20]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
L**2

TypeError: ignored

In [0]:
#squaring doesn't work for list

In [0]:
L2 = []

for e in L:
  L2.append(e*e)

In [24]:
L2

[1, 4, 9, 16, 25]

In [0]:
#to make the element wise squaring possible, we need to create a for loop as above


In [25]:
#in arrays, however the elementwise squaring is easy
A**2

array([1, 4, 9])

In [28]:
#for elemntwise operations arrays are good and they treat each element like a vector, for loops are slow in python
#the operations on array are easily understandable and counter intuitive
#element wise square root, log, exponential:
np.sqrt(A)
np.log(A)
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])