<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Linear_system_solve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
#finding x when we know A and b [ax = a^-1 b]
A= np.array([[1,2],[3,4]])

In [2]:
A

array([[1, 2],
       [3, 4]])

In [0]:
b= np.array([3,4])

In [4]:
b

array([3, 4])

In [0]:
x= np.linalg.inv(A).dot(b)

In [7]:
x

array([-2. ,  2.5])

In [0]:
#numpy has an easy function for that

x= np.linalg.solve(A,b)

In [9]:
x

array([-2. ,  2.5])