<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Numerous matrix operations

A = np.array([[3,4],[5,6]])
#inverse of a matrix
Ainv = np.linalg.inv(A)

In [2]:
Ainv

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [3]:
#determinant of a matrix

detA = np.linalg.det(A)

detA

-1.9999999999999971

In [4]:
#diagonal of a matrices

np.diag(A)

array([3, 6])

In [5]:
#when we pass 1d array in the above function we get a 2 d array. all the non diagonal elements a zero

np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
#outer Product

a= np.array([4,5])
b= np.array([7,6])

np.outer(a,b)

array([[28, 24],
       [35, 30]])

In [7]:
#inner product is same as dot product

np.inner(a,b)

58

In [0]:
#summing the diagonal elements

np.diag(a).sum()



In [0]:
l = np.diag([1,2])

In [15]:
l

array([[1, 0],
       [0, 2]])

In [16]:
#trace sums the diagonal elements

np.trace(l)

3

In [0]:
#eigen value and eigen vector

X = np.random.randn(100,3)

#calculating the covarience

cov = np.cov(X)

In [18]:
cov

array([[ 0.2846165 ,  0.55369654, -0.46470167, ...,  0.57772744,
         0.44517591,  0.38269553],
       [ 0.55369654,  1.80765047, -1.18139351, ...,  1.22144303,
         1.15519345,  2.55911755],
       [-0.46470167, -1.18139351,  0.86404174, ..., -0.98030166,
        -0.83663634, -1.31383054],
       ...,
       [ 0.57772744,  1.22144303, -0.98030166, ...,  1.18571756,
         0.94224086,  1.01907739],
       [ 0.44517591,  1.15519345, -0.83663634, ...,  0.94224086,
         0.81076064,  1.31685322],
       [ 0.38269553,  2.55911755, -1.31383054, ...,  1.01907739,
         1.31685322,  5.02232683]])

In [19]:
cov.shape

(100, 100)

In [20]:
#If it's 100 x 100, then it is wrong

#we need to transpose it

cov = np.cov(X.T)

cov

array([[ 1.02352756,  0.19868294,  0.00614655],
       [ 0.19868294,  1.14452127, -0.05780714],
       [ 0.00614655, -0.05780714,  0.81100527]])

In [21]:
#functions for calculating eigen values and eigen vectors
# eigh is used for calculating it in hermitian marix

np.linalg.eigh(cov)

(array([0.78952264, 0.89400984, 1.29552162]),
 array([[-0.28467591, -0.75848202, -0.58622918],
        [ 0.3071933 ,  0.50710359, -0.80528146],
        [ 0.90807043, -0.4093299 ,  0.08864042]]))

In [22]:
# eig is used for calculating it in symetric marix

np.linalg.eig(cov)

(array([1.29552162, 0.89400984, 0.78952264]),
 array([[ 0.58622918,  0.75848202, -0.28467591],
        [ 0.80528146, -0.50710359,  0.3071933 ],
        [-0.08864042,  0.4093299 ,  0.90807043]]))