<a href="https://colab.research.google.com/github/Akif-Mufti/Deep-learning-2.0/blob/master/Matrices_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#vector is a one dimensional numpy array [1 d object]
#matrices is two dimensional numpy array [2 d object]


#official documentation recommends not to use matrix, but to convert them into array
import numpy as np
M = np.array([[1,2],[3,4]])

L= [[1,2],[3,4]]

In [2]:
#get the elements from first list

L[0]

[1, 2]

In [3]:
#get first element from the first list

L[0][0]

1

In [4]:
#similarly for array
M[0][0]

1

In [5]:
#another notation

M[0,0]

1

In [0]:
#another actual matrix data type in numpy
#although a matrix might look like an array but it is different.


M2 = np.matrix([[1,2],[3,4]])

In [7]:
M2

matrix([[1, 2],
        [3, 4]])

In [0]:
#recommended wayis to convert the matrix into array

B= np.array(M2)

In [10]:
B

array([[1, 2],
       [3, 4]])

In [11]:
#transpose it
B.T

array([[1, 3],
       [2, 4]])